// Frond_Vue/App.vue
<script setup>
import { ref } from "vue";
import axios from "axios";

const query = ref("");
const response = ref("");

const sendQuery = async () => {
  try {
    const res = await axios.post("http://127.0.0.1:5001/ask", { query: query.value });
    response.value = res.data.answer;
  } catch (error) {
    console.error("Error:", error);
    response.value = "Error connecting to backend.";
  }
};
</script>

<template>
  <div class="container">
    <h1>Chatbot</h1>
    <input v-model="query" type="text" placeholder="Ask something..." />
    <button @click="sendQuery">Ask</button>
    <p>Response: {{ response }}</p>
  </div>
</template>

<style>
.container {
  font-family: Arial, sans-serif;
  text-align: center;
  margin-top: 50px;
}
input {
  padding: 10px;
  margin: 10px;
  width: 300px;
}
button {
  padding: 10px;
  background-color: blue;
  color: white;
  border: none;
  cursor: pointer;
}
</style>

// Frontend_React/App.js
import React, { useState } from "react";
import axios from "axios";
import { BrowserRouter as Router, Routes, Route, Link } from "react-router-dom";

function WelcomePage() {
  return (
    <div>
      <h1>Welcome to Baroz AI</h1>
      <Link to="/chat">
        <button>Start Chat</button>
      </Link>
    </div>
  );
}

function ChatPage() {
  const [query, setQuery] = useState("");
  const [response, setResponse] = useState("");

  const sendQuery = async () => {
    try {
      const res = await axios.post("http://localhost:5001/ask", { query });
      setResponse(res.data.answer);
    } catch (error) {
      setResponse("Error fetching response.");
    }
  };

  return (
    <div>
      <h1>Baroz AI Chat</h1>
      <input
        type="text"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Ask me something..."
      />
      <button onClick={sendQuery}>Send</button>
      <p>Response: {response}</p>
    </div>
  );
}

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<WelcomePage />} />
        <Route path="/chat" element={<ChatPage />} />
      </Routes>
    </Router>
  );
}

export default App;
